### ISSUE TITLE
output capture like rails templates

### ISSUE THREAD

**Issue by francescoagati** [RealyUniqueName/HHP#1]
Hi,
is possible to do something like in rails helper, with anonymous function and block capture output

this is an example  

```
<%= navbar do %>
  <%= vertical do %>
    <%= form_for User.new do |f| %>
    <%= f.email_field :email %>
      <%= f.submit 'Sign in' %>
    <% end %>
  <% end %>
<% end %>
```

http://fullscreen.github.io/bh/#form-navbar

**Comment by RealyUniqueName** [comment]
I'm not familiar with ruby and rails.
But if you can write analogue of above code in Haxe, then you can write it in HHP templates.
